COMPILER=pdflatex
FLAGS=-jobname=diploma
SOURCE=00-diploma.tex

default:
	$(COMPILER) $(FLAGS) $(SOURCE)
	$(COMPILER) $(FLAGS) $(SOURCE)
	$(COMPILER) $(FLAGS) $(SOURCE)

clean:
	rm -f *.{aux,bbl,blg,log,out,toc,gz}
